# RecipeVault/pubspec.yaml
name: recipe_vault
version: 0.2.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ">=3.15.0 <5.0.0"
  firebase_auth: ">=5.6.2 <7.0.0" 
  cloud_firestore: ">=5.6.10 <7.0.0"
  provider: ^6.1.1
  intl: any
  google_mobile_ads: ^6.0.0
  shared_preferences: ^2.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=3.0.1 <7.0.0"
  firebase_core_platform_interface: any