// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg_dTyn77dEh3ILyhEWJmKgeNn26q1Ix0',
    appId: '1:1045821219124:web:e8c484d0a76670a0e58561',
    messagingSenderId: '1045821219124',
    projectId: 'free-recipe-vault',
    authDomain: 'free-recipe-vault.firebaseapp.com',
    storageBucket: 'free-recipe-vault.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT2LyxxI9BIOl27rSBbISt6IuA2_jOmPY',
    appId: '1:1045821219124:android:4a5cb3d1166b21f0e58561',
    messagingSenderId: '1045821219124',
    projectId: 'free-recipe-vault',
    storageBucket: 'free-recipe-vault.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtIo8RTvmu_EsT7h_A5jqPZ6vBMKfIUqo',
    appId: '1:1045821219124:ios:ba10336ac4c48004e58561',
    messagingSenderId: '1045821219124',
    projectId: 'free-recipe-vault',
    storageBucket: 'free-recipe-vault.firebasestorage.app',
    iosClientId: '1045821219124-ej9923dl4knto6hfspd0rlrkj9ht3865.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeVault',
  );
}
