# ------------------------------------------------------------------
# .github/workflows/flutter_ci.yml
#   - ジョブ ❶ analyze   : lint を高速チェック
#   - ジョブ ❷ test      : ユニットテスト + カバレッジ（Codecov）
#     ❷ の中で ★ pub outdated を実行して “古い依存” を検知
#   ※ test は analyze が通った場合だけ実行 (needs:)
# ------------------------------------------------------------------

name: Flutter CI

# main への push / PR 作成で実行
on: [push, pull_request]

# ----------------------------------------------------
# ❶  静的解析（lint）ジョブ
# ----------------------------------------------------
jobs:
  analyze:
    name: Analyze (Flutter)
    runs-on: ubuntu-latest

    steps:
      # 1) ソース取得
      - uses: actions/checkout@v4

      # 2) Flutter SDK + キャッシュ (~/.pub-cache)
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.6'   # プロジェクトのバージョン
          cache: true                 # Pub キャッシュを自動保存

      # 3) 依存取得
      - run: flutter pub get

      # 4) 静的解析（info レベルもエラー扱い）
      - run: flutter analyze --no-pub --fatal-infos

# ----------------------------------------------------
# ❷  テスト & カバレッジ ジョブ
#     - analyze が成功したら実行 (needs: analyze)
# ----------------------------------------------------
  test:
    name: Test & Coverage (Flutter)
    needs: analyze
    runs-on: ubuntu-latest

    steps:
      # 1) ソース取得
      - uses: actions/checkout@v4

      # 2) Flutter SDK + キャッシュ
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.6'
          cache: true

      # 3) 依存取得
      - run: flutter pub get

      # 4) ★ 古い依存パッケージがないかチェック（警告のみで CI は落とさない）
      - run: flutter pub outdated --mode=null-safety || true
        name: Check outdated packages

      # 5) ユニットテスト + カバレッジ生成
      - run: flutter test --coverage

      # 6) カバレッジを Codecov へアップロード
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}   # Public repoなら token 行は不要
        with:
          files: coverage/lcov.info
          slug: gotty412/RecipeVault
          # verbose: true   # ← 詳細ログを出したい場合。不要なら削除